<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EntrepriseProfil extends \App\Entity\EntrepriseProfil implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activityArea' => [parent::class, 'activityArea', null],
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'applications' => [parent::class, 'applications', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'offers' => [parent::class, 'offers', null],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null],
        "\0".parent::class."\0".'zipCode' => [parent::class, 'zipCode', null],
        'activityArea' => [parent::class, 'activityArea', null],
        'address' => [parent::class, 'address', null],
        'applications' => [parent::class, 'applications', null],
        'city' => [parent::class, 'city', null],
        'country' => [parent::class, 'country', null],
        'description' => [parent::class, 'description', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'logo' => [parent::class, 'logo', null],
        'name' => [parent::class, 'name', null],
        'offers' => [parent::class, 'offers', null],
        'phoneNumber' => [parent::class, 'phoneNumber', null],
        'slug' => [parent::class, 'slug', null],
        'user' => [parent::class, 'user', null],
        'website' => [parent::class, 'website', null],
        'zipCode' => [parent::class, 'zipCode', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
