<?php

namespace Container2Vl4tQY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Am4nAQAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.am4nAQA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.am4nAQA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'entrepriseProfilRepository' => ['privates', 'App\\Repository\\EntrepriseProfilRepository', 'getEntrepriseProfilRepositoryService', true],
            'session' => ['privates', '.errored..service_locator.am4nAQA.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.am4nAQA": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
            'tokenStorageInterface' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'uploadFilesService' => ['services', 'App\\Services\\UploadFilesService', 'getUploadFilesServiceService', true],
        ], [
            'em' => '?',
            'entrepriseProfilRepository' => 'App\\Repository\\EntrepriseProfilRepository',
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'tokenStorageInterface' => '?',
            'uploadFilesService' => 'App\\Services\\UploadFilesService',
        ]);
    }
}
