<?php

namespace ContainerVHMHM9o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1sPo2aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1s_po2a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1s_po2a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userProfilRepository' => ['privates', 'App\\Repository\\UserProfilRepository', 'getUserProfilRepositoryService', true],
        ], [
            'userProfilRepository' => 'App\\Repository\\UserProfilRepository',
        ]);
    }
}
