<?php

namespace ContainerVHMHM9o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Ka9NspService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Ka9Nsp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Ka9Nsp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entrepriseProfil' => ['privates', '.errored..service_locator..Ka9Nsp.App\\Entity\\EntrepriseProfil', NULL, 'Cannot autowire service ".service_locator..Ka9Nsp": it needs an instance of "App\\Entity\\EntrepriseProfil" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entrepriseProfil' => 'App\\Entity\\EntrepriseProfil',
        ]);
    }
}
