<?php

namespace ContainerVHMHM9o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrepriseProfilService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..Ka9Nsp.App\Entity\EntrepriseProfil' shared service.
     *
     * @return \App\Entity\EntrepriseProfil
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..Ka9Nsp": it needs an instance of "App\\Entity\\EntrepriseProfil" but this type has been excluded in "config/services.yaml".');
    }
}
